### ISSUE TITLE
Read run-time configuration using a configuration library

### ISSUE THREAD

**Issue by bignose-debian** [cbodnaruk/megagame-dashboard#24]
Application run-time configuration can be read from configuration files, environment variables, and command-line options. There are existing libraries that implement this well.

By re-working the run-time configuration to use an API for that purpose, we can extend the configuration schema easily and keep configuration well-defined.

**Comment by bignose-debian** [comment]
I have a [merge request at my personal fork](https://codeberg.org/bignose/megagame-dashboard/pulls/3) to address this, implemented using the Convict library.

(Note that the merge request there depends on an [issue to refine Git ignore-pattern configuration](#23).)

**Comment by cbodnaruk** [comment]
Merged
