### ISSUE TITLE
Schema and example data

### ISSUE THREAD

**Issue by bignose-debian** [cbodnaruk/megagame-dashboard#26]
The scripts to set up the database schema, belong in the project source code. This is typically done with "database migration" scripts, to automate changes forward and reverse.

To test the schema, some initial example data will also be helpful.

**Comment by bignose-debian** [comment]
I have a [merge request at my personal fork](https://codeberg.org/bignose/megagame-dashboard/pulls/4) to address this, with a custom "migration" (SQL script forward and reverse).

Another script in the same merge request provides test data, by populating the tables (again via SQL script) for a 'demo' dashboard.

**Comment by cbodnaruk** [comment]
Merged
