### ISSUE TITLE
Document how to install and run the application

### ISSUE THREAD

**Issue by bignose-debian** [cbodnaruk/megagame-dashboard#27]
The project source code currently has no instructions for what is needed to set up, install, and run the application.

Create an INSTALL document with the essential instructions.

**Comment by bignose-debian** [comment]
I have a [merge request at my personal fork](https://codeberg.org/bignose/megagame-dashboard/pulls/5) to address this.

Note that the document in that merge request assumes the existence of schema migration scripts and example data populate scripts, as defined in [an earlier merge request](https://codeberg.org/bignose/megagame-dashboard/pulls/4).

**Comment by cbodnaruk** [comment]
Merged
