### ISSUE TITLE
Encapsulate database connection in a module

### ISSUE THREAD

**Issue by bignose-debian** [cbodnaruk/megagame-dashboard#28]
The database connection is currently hard-coded as PostgreSQL in the main server code.

Instead, we can begin extracting the database behaviour to its own module to allow separation of the database specifics from the application logic.

**Comment by bignose-debian** [comment]
I have a [merge request at my personal fork](https://codeberg.org/bignose/megagame-dashboard/pulls/6) to address this.

**Comment by cbodnaruk** [comment]
Merged
